version: '3'

services:
  model-training:
    build: .
    volumes:
      - .:/app
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
    entrypoint: ["sh", "-c", "while true; do python main.py; sleep 3600; done"]
    restart: always